### ISSUE TITLE
Python: gherkin.pickles is not present in pypi package

### ISSUE THREAD

**Issue by ianmarcinkowski** [cucumber/gherkin#200] opened 2016-04-05 14:45 UTC
Perhaps I am missing something obvious, but the package that gets installed when running `pip install gherkin-official` does not contain the `pickles` sub-package.

Here are the steps I am taking to install gherkin:

```
ian@mymachine ~
:% mkvirtualenv example
[...]
(example)ian@mymachine ~
:% pip install --upgrade pip 
[...]
(example)ian@mymachine ~
:% pip install gherkin-official
Collecting gherkin-official
  Using cached gherkin-official-3.2.0.tar.gz
Installing collected packages: gherkin-official
  Running setup.py install for gherkin-official ... done
Successfully installed gherkin-official-3.2.0
(example)ian@mymachine ~
:% cdsitepackages 
(example)ian@mymachine ~/.virtualenvs/example/lib/python2.7/site-packages
:% ls
easy_install.py  easy_install.pyc  gherkin  gherkin_official-3.2.0-py2.7.egg-info  _markerlib  pip  pip-8.1.1.dist-info  pkg_resources  setuptools  setuptools-18.4.dist-info
(example)ian@mymachine ~/.virtualenvs/example/lib/python2.7/site-packages
:% cd gherkin
(example)ian@mymachine ~/.virtualenvs/example/lib/python2.7/site-packages/gherkin
:% ls
ast_builder.py   ast_node.pyc          count_symbols_py2.pyc       count_symbols.pyc  errors.py               gherkin_line.py   __init__.pyc  token_formatter_builder.py   token_matcher.pyc  token_scanner.py
ast_builder.pyc  count_symbols.py      count_symbols_py3_plus.py   dialect.py         errors.pyc              gherkin_line.pyc  parser.py     token_formatter_builder.pyc  token.py           token_scanner.pyc
ast_node.py      count_symbols_py2.py  count_symbols_py3_plus.pyc  dialect.pyc        gherkin-languages.json  __init__.py       parser.pyc    token_matcher.py             token.pyc
(example)ian@mymachine ~/.virtualenvs/example/lib/python2.7/site-packages/gherkin
```

Pulling down the gherkin-python repository (https://github.com/cucumber/gherkin-python) and installing that local directory in my virutalenv solves the problem.

Edit: The tarball hosted on pypi.python.org (https://pypi.python.org/pypi/gherkin-official/) does not contain the `pickles` subdirectory.

**Comment by aslakhellesoy** [comment] 2016-04-05 14:51
Dupe of #156 and #157, which are fixed on master. See `CHANGELOG.md`

**Closed by aslakhellesoy** 2016-04-05 14:51 UTC
