### ISSUE TITLE
Parsing error with comment only feature files

### ISSUE THREAD

**Issue by enkessler** [cucumber/gherkin#179] opened 2023-09-30 21:32 UTC
### 👓 What did you see?

I encountered a parsing error when running a Cucumber suite that included a feature file containing only a comment line.

`unexpected end of file, expected: #Language, #TagLine, #FeatureLine, #Comment, #Empty (Cucumber::Core::Gherkin::ParseError)`

### ✅ What did you expect to see?

I expected the file to parse cleanly and have no impact on the Cucumber execution (no errors, no pickles, etc.)

### 📦 Which tool/library version are you using?

OS: Windows
Language: Ruby
Cucumber version: various, as needed for whatever version of `cucumber-gherkin` that I was using
Gherkin versions: 9-27. All versions of `cucumber-gherkin` are affected

### 🔬 How could we reproduce it?

1. Have a feature file that only contains comments
"my_great_idea.feature"
```
# Must write this idea down before I go to lunch and forget
```
3. Attempt to run the feature
`cucumber my_great_idea.feature`
4. Get a parsing error
`unexpected end of file, expected: #Language, #TagLine, #FeatureLine, #Comment, #Empty (Cucumber::Core::Gherkin::ParseError)`

### 📚 Any additional context?

Given that the parsing error explicitly lists `#Comment` tokens as a valid expectation at that point in the file, I am under the impression that the example feature is intended to be syntactically valid and that this is a bug in the parser.
----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by luke-hill** [comment] 2023-10-27 09:25
This sounds a legit issue. However I have just re-tested this on cucumber 9.0.2 and I cannot reproduce it.

However I'm not certain we have done many / all fixes recently. My only thought is that we are now restricting gherkin quite aggressively in cucumber ruby because of some new bug fixes / refactors, maybe this has implicitly fixed this?

Can you re-test using cucumber ruby 9.0.2 please @enkessler

**Comment by enkessler** [comment] 2023-11-25 20:22
For `cucumber` `9.0.2` it works fine. After doing a `bundle update` It looks like it is only continuing to happen for older versions of Cucumber (e.g. `6.x`, `2.x`). So updating Cucumber as much as possible did fix the problem, although I am surprised that what presented as a parsing issue appears to instead be a test framework issue instead. A test might need to be added to `cucumber-ruby`.

In any case, I will continue to work around this issue by having non-empty feature files because I need to be able to use both newer and older versions of Cucumber.

**Comment by luke-hill** [comment] 2023-11-27 08:52
So we have a new way of doing "things" in cucumber that is presented in the CCK. We are currently looking to do 2 things.

1 - Evaluate our CCK try add new items (I'll make a note to ensure we have a comment based CCK if we don't already)
2 - Port the CCK "inside" cucumber-ruby. Currently js sits inside cucumber-js, cucumber-jvm is a WIP (half n half), cucumber-ruby sits wholly outside.

If you want to manage / check progress or contribute feel free to

**Comment by mattwynne** [comment] 2023-11-27 18:53
> I am surprised that what presented as a parsing issue appears to instead be a test framework issue instead.

Looking at the error message, It strikes me as more likely that this was indeed a parsing issue, in an older version of the Gherkin parser being used by the older version of Cucumber you were using.

If you have the capacity to investigate the details a bit more @enkessler and send a PR to improve the UX for these older versions of Cucumber, please go ahead. I don't see an actionable change here to the Gherkin library though so I think we need to close this issue.

**Comment by luke-hill** [comment] 2023-11-28 09:06
Hi @mattwynne - I was planning on keeping this open as a note to get the 2 things done. Once I've got those two things done I think we should close this as then we'll be able to monitor this better

**Comment by Kingdutch** [comment] 2023-11-29 18:13
I had something similar using the `cucumber/gherkin` package in PHP version 27.0.0

The following gave an error:

```gherkin
@tags here
Feature: Feature decription
  # This causes an error
  Benefit: Some benefit
  Role: To a user type
  Goal/desire: That wants to achieve something

  Scenario: Rest of the file omitted
```

The error is reported for the lines that have "Benefit", "Role", "Goal". If I remove the `# This causes an error` line then everything works as expected.

**Comment by luke-hill** [comment] 2024-08-15 08:41
update to @enkessler and any other watchers.

We are close to having a "Blank" feature being CCK described. From there we will then look to get things CCK conformant across all CCK implementors (Currently JS and Ruby, with JVM closely aligned).

In terms of having a "Comment only" feature - I'd personally be against this, because again I feel as though the error being reported is valid. Feature files ideally should start with a valid shebang line (Such as the language comment), or just start with a tag / feature. I'd be inclined to lean on the error being reported here.

**Comment by luke-hill** [comment] 2024-08-15 08:43
@Kingdutch - I just spotted this. This again is something I haven't spotted and could be something bespoke to php.

This issue was specifically about blank / empty feature files, which we have nearly fixed up. Yours is specifically about comments full stop across the file

**Comment by luke-hill** [comment] 2024-11-18 10:11
Closed by https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/empty/empty.feature

The ideal way of doing a blank scenario is the above @enkessler and should be handled consistently across flavours of cucumber

**Closed by luke-hill** 2024-11-18 10:11 UTC
Labels: :robot: dependencies
