### ISSUE TITLE
Background.feature is nil (in Cucumber 2.0)

### ISSUE THREAD

**Issue by e2** [cucumber/gherkin#334] opened 2015-03-29 15:38 UTC
Hi!

I'm trying to make my custom formatter to work again, but feature is nil here: https://github.com/guard/guard-cucumber/blob/master/lib/guard/cucumber/notification_formatter.rb#L47

(I'm using cucumber 2.0 and gherkin 2.12.2)

My feature file is pretty standard:

```cucumber
Feature: using Guard API

  In order to reuse existing Guard functionality
  As a user
  I want to call Guard API without Guard

  Background: Guard is installed through bundler
    Given my Gemfile includes "gem 'rake'"
    And Guard is bundled using source
   # (...)
```

Is `Background#feature` supposed to be available?

I can work around this - I just wanted to report this and/or find out what's recommended/etc.

**Comment by brasmusson** [comment] 2015-03-29 18:45
Closing this in favour of cucumber/cucumber-ruby-core#84 (where the root cause lies).

**Closed by brasmusson** 2015-03-29 18:45 UTC
