### ISSUE TITLE
Gherkin releases on pypi

### ISSUE THREAD

**Issue by tra-github** [cucumber/gherkin#119] opened 2023-06-09 07:45 UTC
Hi,
I notice gherkin on pypi is still version 24.1.0. Are latest versions no longer released on pypi?
Sylvie

**Comment by mpkorstanje** [comment] 2023-07-07 10:15
No. Not at this moment.

- There aren't enough drive by contributors to help keep us up to date with Pythons state of the art. 
- The Cucumber Project currently permanent maintainers (see https://mattwynne.net/new-beginning).

Duplicate of #40.

**Closed by mpkorstanje** 2023-07-07 10:15 UTC
